#ifndef BOARD_TL751X_EVK_H
#define BOARD_TL751X_EVK_H

// 引脚定义（映射到芯片实际GPIO）
#define BOARD_LED0_PIN    12  // TL751X_EVK的LED连接到GPIO12
#define BOARD_BUTTON0_PIN 13 // TL751X_EVK的按键连接到GPIO13

// GPIO配置（LED为输出，按键为输入）
#define LED0_CONFIG { .dir = HAL_GPIO_DIR_OUTPUT }
#define BUTTON0_CONFIG { .dir = HAL_GPIO_DIR_INPUT }

#endif // BOARD_TL751X_EVK_H
